name: Security audit
on:
  workflow_call:

jobs:
  audit:
    name: Audit dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Rust
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable

      - name: Run audit
        run: |
          cargo install cargo-audit
          cargo audit

