name: Release Please

on:
  workflow_call:
    inputs:
      package-name:
        required: true
        type: string

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v4
        with:
          release-type: rust
          package-name: ${{ inputs.package-name }}
